### ISSUE TITLE
Release advice

### ISSUE THREAD

**Issue by katrinleinweber** [johanneswerner/mPies#2]
Due to https://github.com/johanneswerner/mPies/pull/1#issuecomment-446857750 I would like to lay out a few options:

Yes, starting with a `0.9` is a good idea, because you can then generate a version-independent [Zenodo-DOI for this repo](https://guides.github.com/activities/citable-code/), which you then can add back to your [`README.md`](https://github.com/johanneswerner/mPies/edit/master/README.md) before releasing the `1.0`. See https://github.com/TIBHannover/BacDiveR/#bacdiver--- for example.

If you go that way, and use GitHub's [`Create a new release`](https://github.com/johanneswerner/mPies/releases/new) I would also recommend to copy-paste the main points from the README into the release text, along with maybe version-specific changelog. That way, both show up on the Zenodo page, while you can remove the non-changelog from the GitHub release description again.

Cheers :-)

**Comment by johanneswerner** [comment]
When would be the time to create the Zenodo-DOI? With tag 0.9 or 1.0?

**Comment by katrinleinweber** [comment]
With 0.9. Tagging is part of GitHub's [`Create a new release`](https://github.com/johanneswerner/mPies/releases/new) process, so you don't need to do that with the Git CLI and then push a locally created tag.

**Comment by johanneswerner** [comment]
great Zenodo error. 

```
{
    "errors": "Unknown error occured."
}
```

I have to shift fixing this for after my vacation.

**Comment by katrinleinweber** [comment]
Damn :-( I've never seen this before. You can tinker around in their https://sandbox.zenodo.org/ until https://guides.github.com/activities/citable-code/ works (except for actually displaying the generated DOI there).

I would try revokating all of Zenodos [OAuth or app](https://github.com/settings/applications) access rights and then go through the process again, using a dedicated Zenodo account (not their GitHub-based login). But I'm not sure what's causing the error.

**Comment by katrinleinweber** [comment]
Also: Since your release title will be your Zenodo record title (after "johanneswerner/mPies: ...") , you may want to pick something else than "mPies ... release" for the 1.0 release to avoid the duplicated package name ;-)

**Comment by johanneswerner** [comment]
What would be a better release name?

**Comment by katrinleinweber** [comment]
I'm [still experimenting](https://github.com/TIBHannover/BacDiveR/releases)... Quickly [looking into other popular GH-Z-syncers](https://github.com/search?q=%22zenodo.org%2Fbadge%2FDOI%22+stars%3A%3E10&type=Code) reveals that [most](https://zenodo.org/search?page=1&size=20&q=gwpy) [seem](https://zenodo.org/search?page=1&size=20&q=astropy&type=software) [to](https://zenodo.org/search?page=1&size=20&q=galaxy&type=software) [use](https://zenodo.org/search?page=1&size=20&q=matplotlib&type=software) simply the version number.

Maybe `GitHub description (version...)` is best in terms of informativeness & SEO.

**Comment by johanneswerner** [comment]
I added a new release and this time I obtained a DOI from Zenodo (also added to the `README.md`).

Thank you again! Closing ...
